/*Base Code*/

/*
 This Program has been redesigned by Matthew Karton - https://www.youtube.com/channel/UCMerT5HB7zWz52PLpoCpQGg?view_as=subscriber
 Orginal Creator of the Code` is Drone How - https://www.youtube.com/channel/UChpECbbdhDvlNxg1IpEwcyw/featured

 This programe is designed for some DIY Christmas lights;
 LEDR/G# = LED - Colour = R/G - Number
 Design of Sequence is able to be designed at; void loopp()
 if you are adding more to this design please add the int function before void setup and the pinMode in void setup

 If you would like to see this code in action please refer to the video created by Matthew Karton and Drone How
 Video Featured in - https://youtu.be/X05ff_4EcYI

 Feel Free to use this code for personal use if you are creating content with this code personally and or commerically please acknowledge the orginal creator(s)
 Enjoy Coding! 
 */
 
int LEDR1 = 3;
int LEDG1 = 4;
int LEDR2 = 5;
int LEDG2 = 6;
int LEDR3 = 7;
int LEDG3 = 8;
int LEDR4 = 9;
int LEDG4 = 10;

void setup() {
  pinMode(LEDR1, OUTPUT);
  pinMode(LEDG1, OUTPUT);
  pinMode(LEDR2, OUTPUT);
  pinMode(LEDG2, OUTPUT);
  pinMode(LEDR3, OUTPUT);
  pinMode(LEDG3, OUTPUT);
  pinMode(LEDR4, OUTPUT);
  pinMode(LEDG4, OUTPUT);
}


void loop() {
  digitalWrite(LEDR1, HIGH); /*Sequence Lighting Each LED Once then off*/
  delay(100);
  digitalWrite(LEDG1, HIGH);
  delay(100);
  digitalWrite(LEDR2, HIGH);
  delay(100);
  digitalWrite(LEDG2, HIGH);
  delay(100);
  digitalWrite(LEDR3, HIGH);
  delay(100);
  digitalWrite(LEDG3, HIGH);
  delay(100);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Sequence Lighting Each LED Once then off*/
  delay(100);
  digitalWrite(LEDG1, HIGH);
  delay(100);
  digitalWrite(LEDR2, HIGH);
  delay(100);
  digitalWrite(LEDG2, HIGH);
  delay(100);
  digitalWrite(LEDR3, HIGH);
  delay(100);
  digitalWrite(LEDG3, HIGH);
  delay(100);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Sequence Lighting Each LED Once then off*/
  delay(100);
  digitalWrite(LEDG1, HIGH);
  delay(100);
  digitalWrite(LEDR2, HIGH);
  delay(100);
  digitalWrite(LEDG2, HIGH);
  delay(100);
  digitalWrite(LEDR3, HIGH);
  delay(100);
  digitalWrite(LEDG3, HIGH);
  delay(100);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Sequence Lighting Each LED Once then off*/
  delay(100);
  digitalWrite(LEDG1, HIGH);
  delay(100);
  digitalWrite(LEDR2, HIGH);
  delay(100);
  digitalWrite(LEDG2, HIGH);
  delay(100);
  digitalWrite(LEDR3, HIGH);
  delay(100);
  digitalWrite(LEDG3, HIGH);
  delay(100);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Sequence Lighting Each LED Once then off*/
  delay(100);
  digitalWrite(LEDG1, HIGH);
  delay(100);
  digitalWrite(LEDR2, HIGH);
  delay(100);
  digitalWrite(LEDG2, HIGH);
  delay(100);
  digitalWrite(LEDR3, HIGH);
  delay(100);
  digitalWrite(LEDG3, HIGH);
  delay(100);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Sequence Lighting Each LED Once then off*/
  delay(100);
  digitalWrite(LEDG1, HIGH);
  delay(100);
  digitalWrite(LEDR2, HIGH);
  delay(100);
  digitalWrite(LEDG2, HIGH);
  delay(100);
  digitalWrite(LEDR3, HIGH);
  delay(100);
  digitalWrite(LEDG3, HIGH);
  delay(100);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Sequence Lighting Each LED Once then off*/
  delay(100);
  digitalWrite(LEDG1, HIGH);
  delay(100);
  digitalWrite(LEDR2, HIGH);
  delay(100);
  digitalWrite(LEDG2, HIGH);
  delay(100);
  digitalWrite(LEDR3, HIGH);
  delay(100);
  digitalWrite(LEDG3, HIGH);
  delay(100);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /*Red Blinking x5*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH); /*Green Blinking x5*/
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* on, on + off, off x3*/
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH);
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  delay(100);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  delay(100);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  digitalWrite(LEDR1, HIGH); /* All Flash */
  digitalWrite(LEDR2, HIGH);
  digitalWrite(LEDR3, HIGH);
  digitalWrite(LEDR4, HIGH);
  digitalWrite(LEDG1, HIGH);
  digitalWrite(LEDG2, HIGH);
  digitalWrite(LEDG3, HIGH);
  digitalWrite(LEDG4, HIGH);
  delay(100);
  digitalWrite(LEDR1, LOW);
  digitalWrite(LEDR2, LOW);
  digitalWrite(LEDR3, LOW);
  digitalWrite(LEDR4, LOW);
  digitalWrite(LEDG1, LOW);
  digitalWrite(LEDG2, LOW);
  digitalWrite(LEDG3, LOW);
  digitalWrite(LEDG4, LOW);
  delay(100);
  
}
